; PlatformIO Project Configuration File
;
; Clone the Neffy_UART_Interface repository and open this folder as a PlatformIO project.
; The library is referenced from the repository root via lib_extra_dirs.

[common]
platform = espressif32
board = neffy_mainboard
board_build.mcu = esp32s3
framework = arduino
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
board_build.psram = disabled
monitor_speed = 1000000
[env:neffy_sender]
platform = espressif32
board = esp32dev
board_build.mcu = esp32
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<sender/>
build_flags = -I${PROJECT_SRC_DIR}/shared

[env:neffy_receiver]
extends = common
build_src_filter = -<*> +<receiver/> +<shared/>
build_flags = -I${PROJECT_SRC_DIR}/shared
